# PRSIEM-NET-6 lab
#
# ISEP, 2026
# 

LAB_DESCRIPTION=IPv6i/SLACC lab
LAB_VERSION=20260513

da1[0]=netA
da1[image]='miguelleitao/host-isep'
da2[0]=netA
da2[image]='miguelleitao/host-isep'
da3[0]=netA
da3[image]='miguelleitao/host-isep'

db1[0]=netB
db1[image]='miguelleitao/host-isep'
db2[0]=netB
db2[image]='miguelleitao/host-isep'
db3[0]=netB
db3[image]='miguelleitao/host-isep'

ra[0]=netA
ra[1]=internet
ra[image]='miguelleitao/frr-isep'
rb[0]=netB
rb[1]=internet
rb[image]='miguelleitao/frr-isep'

gwi[0]=backbone
gwi[bridged]=true
gwi[image]='miguelleitao/frr-isep'

srv[0]=backbone
srv[image]='miguelleitao/host-isep'





